// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAanczsv_EbdE_HlThEwSr2qsxsol7kBt0',
    appId: '1:915107551885:web:3cebcc91fdf5043df720c4',
    messagingSenderId: '915107551885',
    projectId: 'mouth-to-mouth',
    authDomain: 'mouth-to-mouth.firebaseapp.com',
    storageBucket: 'mouth-to-mouth.appspot.com',
    measurementId: 'G-R8XMX2T809',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxsHWY9cqTuGx88fjy60xB3slPDWAgsg',
    appId: '1:915107551885:android:b7fa10eeb0319aa0f720c4',
    messagingSenderId: '915107551885',
    projectId: 'mouth-to-mouth',
    storageBucket: 'mouth-to-mouth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6AySbLCRtyTeUmUMzesRFaYrQR1-fqc',
    appId: '1:915107551885:ios:3440e72969116a29f720c4',
    messagingSenderId: '915107551885',
    projectId: 'mouth-to-mouth',
    storageBucket: 'mouth-to-mouth.appspot.com',
    iosBundleId: 'com.mtm.app.mouthToMouth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6AySbLCRtyTeUmUMzesRFaYrQR1-fqc',
    appId: '1:915107551885:ios:3440e72969116a29f720c4',
    messagingSenderId: '915107551885',
    projectId: 'mouth-to-mouth',
    storageBucket: 'mouth-to-mouth.appspot.com',
    iosBundleId: 'com.mtm.app.mouthToMouth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAanczsv_EbdE_HlThEwSr2qsxsol7kBt0',
    appId: '1:915107551885:web:c5bab64c2b07066cf720c4',
    messagingSenderId: '915107551885',
    projectId: 'mouth-to-mouth',
    authDomain: 'mouth-to-mouth.firebaseapp.com',
    storageBucket: 'mouth-to-mouth.appspot.com',
    measurementId: 'G-WHRF4PVK8B',
  );
}
